Change creation of repository and persister
ValeriiSudakov/TaskManager pull request #37
Opened 2020-10-06 10:34 UTC by ValeriiSudakov

- Changed std::function TaskRepository Factory-method to Factory class. Changed implementation in the system.
- Renamed Persister Factory method.

2020-10-06 10:59 UTC, IlliaDmitriiev approved these changes

2020-10-06 12:20 UTC, denhrulyov requested changes

2020-10-06 12:20 UTC, denhrulyov commented on core/Memory_Model/Storage/TaskRepositoryController.h
>  class TaskRepositoryController {
You need virtual functions and destructor to provide any kind of testability and Dependency Injection.

2020-10-08 16:22 UTC, denhrulyov commented on main.cpp
> +  std::unique_ptr<RepositoryController> controller = std::make_unique<TaskRepositoryController>(std::move(std::move(factory)));
Cannot understand why double move std::move(std::move(...)).

2020-10-08 16:25 UTC, denhrulyov commented on tests/core/TestTaskService.cpp
> +    std::unique_ptr<RepositoryController> controller = std::make_unique<TaskRepositoryController>(std::move(std::move(factory)));
Same thing

2020-10-08 20:44 UTC, denhrulyov commented on tests/core/TestTaskService.cpp
> +    auto controller = std::make_unique<TaskRepositoryController>(std::move(std::move(factory)));
What the f* ?

2020-10-08 20:49 UTC, denhrulyov approved these changes

2020-10-08 21:29 UTC, merged